#!/usr/bin/env python3
"""Fetch publications from Google Scholar and write _data/publications.yml.

Run as: python scripts/fetch_scholar.py
Override the author ID via SCHOLAR_ID env var or --scholar-id flag.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import yaml
from scholarly import scholarly

DEFAULT_SCHOLAR_ID = "3cHbgQQAAAAJ"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "_data" / "publications.yml"


def fetch(scholar_id: str) -> list[dict]:
    author = scholarly.search_author_id(scholar_id)
    author = scholarly.fill(author, sections=["publications"])

    pubs: list[dict] = []
    for p in author.get("publications", []):
        try:
            filled = scholarly.fill(p)
        except Exception as e:
            print(f"  ! could not fill pub: {e}", file=sys.stderr)
            continue
        bib = filled.get("bib", {})
        title = bib.get("title", "").strip()
        if not title:
            continue
        pubs.append(
            {
                "title": title,
                "authors": bib.get("author", "").strip(),
                "venue": bib.get("venue") or bib.get("journal") or bib.get("conference") or "",
                "year": str(bib.get("pub_year") or "").strip(),
                "url": filled.get("pub_url") or filled.get("eprint_url") or "",
                "abstract": (bib.get("abstract") or "").strip(),
                "citations": filled.get("num_citations", 0),
            }
        )

    pubs.sort(key=lambda p: (-int(p["year"] or 0), p["title"].lower()))
    return pubs


def write(pubs: list[dict]) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    header = "# Auto-generated by scripts/fetch_scholar.py - do not hand-edit.\n"
    body = yaml.safe_dump(pubs, sort_keys=False, allow_unicode=True, width=100)
    OUTPUT_PATH.write_text(header + body, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--scholar-id",
        default=os.environ.get("SCHOLAR_ID", DEFAULT_SCHOLAR_ID),
    )
    args = ap.parse_args()

    print(f"Fetching publications for Scholar ID: {args.scholar_id}")
    try:
        pubs = fetch(args.scholar_id)
    except Exception as e:
        print(f"FAILED to fetch from Scholar: {e}", file=sys.stderr)
        print("Leaving existing _data/publications.yml unchanged.", file=sys.stderr)
        return 0  # soft-fail so cron does not break the site

    if not pubs:
        print("No publications returned; leaving existing file unchanged.", file=sys.stderr)
        return 0

    write(pubs)
    print(f"Wrote {len(pubs)} publications to {OUTPUT_PATH.relative_to(Path.cwd())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
