#!/usr/bin/env python3
"""Fetch publications and write _data/publications.yml.

Primary source: Semantic Scholar Graph API (free, no auth, fast,
unlike Google Scholar which throttles aggressive scraping).

Run as: python scripts/fetch_scholar.py
Override the author ID via SEMANTIC_SCHOLAR_AUTHOR_ID env var.
"""
from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

import json as _json
import yaml

DEFAULT_AUTHOR_ID = "2000315380"  # Zeman Li @ USC on Semantic Scholar
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "_data" / "publications.yml"

PAPER_FIELDS = (
    "title,authors,year,venue,externalIds,url,openAccessPdf,citationCount,publicationVenue"
)


def _get_json(url: str, retries: int = 3, backoff: float = 5.0) -> dict:
    last_err: Exception | None = None
    for attempt in range(retries):
        try:
            req = Request(url, headers={"User-Agent": "zemanli-website/1.0"})
            with urlopen(req, timeout=30) as resp:
                return _json.loads(resp.read().decode("utf-8"))
        except (HTTPError, URLError) as e:
            last_err = e
            print(f"  ! attempt {attempt + 1}/{retries} failed: {e}", file=sys.stderr)
            time.sleep(backoff * (attempt + 1))
    raise RuntimeError(f"all retries failed: {last_err}")


def fetch(author_id: str) -> list[dict]:
    url = (
        f"https://api.semanticscholar.org/graph/v1/author/{author_id}/papers"
        f"?fields={PAPER_FIELDS}&limit=100"
    )
    payload = _get_json(url)
    raw = payload.get("data", [])

    pubs: list[dict] = []
    for p in raw:
        title = (p.get("title") or "").strip()
        if not title:
            continue
        authors = ", ".join(a.get("name", "") for a in p.get("authors", []) if a.get("name"))
        venue = (p.get("venue") or "").strip()
        if not venue:
            pv = p.get("publicationVenue") or {}
            venue = (pv.get("name") or "").strip() if isinstance(pv, dict) else ""
        ext = p.get("externalIds") or {}
        link = (
            p.get("url")
            or (p.get("openAccessPdf") or {}).get("url")
            or (f"https://arxiv.org/abs/{ext['ArXiv']}" if ext.get("ArXiv") else "")
            or (f"https://doi.org/{ext['DOI']}" if ext.get("DOI") else "")
            or ""
        )
        pubs.append(
            {
                "title": title,
                "authors": authors,
                "venue": venue,
                "year": str(p.get("year") or "").strip(),
                "url": link,
                "citations": int(p.get("citationCount") or 0),
            }
        )

    pubs.sort(key=lambda p: (-int(p["year"] or 0), p["title"].lower()))
    return pubs


def write(pubs: list[dict]) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    header = "# Auto-generated by scripts/fetch_scholar.py - do not hand-edit.\n"
    body = yaml.safe_dump(pubs, sort_keys=False, allow_unicode=True, width=100)
    OUTPUT_PATH.write_text(header + body, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--author-id",
        default=os.environ.get("SEMANTIC_SCHOLAR_AUTHOR_ID", DEFAULT_AUTHOR_ID),
    )
    args = ap.parse_args()

    print(f"Fetching publications for Semantic Scholar author: {args.author_id}")
    try:
        pubs = fetch(args.author_id)
    except Exception as e:
        print(f"FAILED to fetch: {e}", file=sys.stderr)
        print("Leaving existing _data/publications.yml unchanged.", file=sys.stderr)
        return 0  # soft-fail so cron does not break the site

    if not pubs:
        print("No publications returned; leaving existing file unchanged.", file=sys.stderr)
        return 0

    write(pubs)
    print(f"Wrote {len(pubs)} publications to {OUTPUT_PATH.relative_to(Path.cwd())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
